name = "grad_D30_artilleryTweak"
author = "Bernhard aka b-mayr-1984"
prefix = "grad_D30_tweak"
mainprefix = "z"

files = [
    "mod.cpp",
    "logo_active_ca.paa",
    "logo_ca.paa",
    "overview_co.paa",
    "logo_small_ca.paa"
]
